/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoVsebineRouteImport } from './routes/video-vsebine'
import { Route as PonudnikiRouteImport } from './routes/ponudniki'
import { Route as PolitikaZasebnostiRouteImport } from './routes/politika-zasebnosti'
import { Route as PogojiUporabeRouteImport } from './routes/pogoji-uporabe'
import { Route as PodporaMedijuRouteImport } from './routes/podpora-mediju'
import { Route as OglasnaDeskaRouteImport } from './routes/oglasna-deska'
import { Route as NoviceRouteImport } from './routes/novice'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DogodkiRouteImport } from './routes/dogodki'
import { Route as ClankiRouteImport } from './routes/clanki'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NovicaSlugRouteImport } from './routes/novica.$slug'
import { Route as KategorijaSlugRouteImport } from './routes/kategorija.$slug'
import { Route as ClanekSlugRouteImport } from './routes/clanek.$slug'

const VideoVsebineRoute = VideoVsebineRouteImport.update({
  id: '/video-vsebine',
  path: '/video-vsebine',
  getParentRoute: () => rootRouteImport,
} as any)
const PonudnikiRoute = PonudnikiRouteImport.update({
  id: '/ponudniki',
  path: '/ponudniki',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaZasebnostiRoute = PolitikaZasebnostiRouteImport.update({
  id: '/politika-zasebnosti',
  path: '/politika-zasebnosti',
  getParentRoute: () => rootRouteImport,
} as any)
const PogojiUporabeRoute = PogojiUporabeRouteImport.update({
  id: '/pogoji-uporabe',
  path: '/pogoji-uporabe',
  getParentRoute: () => rootRouteImport,
} as any)
const PodporaMedijuRoute = PodporaMedijuRouteImport.update({
  id: '/podpora-mediju',
  path: '/podpora-mediju',
  getParentRoute: () => rootRouteImport,
} as any)
const OglasnaDeskaRoute = OglasnaDeskaRouteImport.update({
  id: '/oglasna-deska',
  path: '/oglasna-deska',
  getParentRoute: () => rootRouteImport,
} as any)
const NoviceRoute = NoviceRouteImport.update({
  id: '/novice',
  path: '/novice',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DogodkiRoute = DogodkiRouteImport.update({
  id: '/dogodki',
  path: '/dogodki',
  getParentRoute: () => rootRouteImport,
} as any)
const ClankiRoute = ClankiRouteImport.update({
  id: '/clanki',
  path: '/clanki',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovicaSlugRoute = NovicaSlugRouteImport.update({
  id: '/novica/$slug',
  path: '/novica/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KategorijaSlugRoute = KategorijaSlugRouteImport.update({
  id: '/kategorija/$slug',
  path: '/kategorija/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClanekSlugRoute = ClanekSlugRouteImport.update({
  id: '/clanek/$slug',
  path: '/clanek/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clanki': typeof ClankiRoute
  '/dogodki': typeof DogodkiRoute
  '/impressum': typeof ImpressumRoute
  '/novice': typeof NoviceRoute
  '/oglasna-deska': typeof OglasnaDeskaRoute
  '/podpora-mediju': typeof PodporaMedijuRoute
  '/pogoji-uporabe': typeof PogojiUporabeRoute
  '/politika-zasebnosti': typeof PolitikaZasebnostiRoute
  '/ponudniki': typeof PonudnikiRoute
  '/video-vsebine': typeof VideoVsebineRoute
  '/clanek/$slug': typeof ClanekSlugRoute
  '/kategorija/$slug': typeof KategorijaSlugRoute
  '/novica/$slug': typeof NovicaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clanki': typeof ClankiRoute
  '/dogodki': typeof DogodkiRoute
  '/impressum': typeof ImpressumRoute
  '/novice': typeof NoviceRoute
  '/oglasna-deska': typeof OglasnaDeskaRoute
  '/podpora-mediju': typeof PodporaMedijuRoute
  '/pogoji-uporabe': typeof PogojiUporabeRoute
  '/politika-zasebnosti': typeof PolitikaZasebnostiRoute
  '/ponudniki': typeof PonudnikiRoute
  '/video-vsebine': typeof VideoVsebineRoute
  '/clanek/$slug': typeof ClanekSlugRoute
  '/kategorija/$slug': typeof KategorijaSlugRoute
  '/novica/$slug': typeof NovicaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clanki': typeof ClankiRoute
  '/dogodki': typeof DogodkiRoute
  '/impressum': typeof ImpressumRoute
  '/novice': typeof NoviceRoute
  '/oglasna-deska': typeof OglasnaDeskaRoute
  '/podpora-mediju': typeof PodporaMedijuRoute
  '/pogoji-uporabe': typeof PogojiUporabeRoute
  '/politika-zasebnosti': typeof PolitikaZasebnostiRoute
  '/ponudniki': typeof PonudnikiRoute
  '/video-vsebine': typeof VideoVsebineRoute
  '/clanek/$slug': typeof ClanekSlugRoute
  '/kategorija/$slug': typeof KategorijaSlugRoute
  '/novica/$slug': typeof NovicaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clanki'
    | '/dogodki'
    | '/impressum'
    | '/novice'
    | '/oglasna-deska'
    | '/podpora-mediju'
    | '/pogoji-uporabe'
    | '/politika-zasebnosti'
    | '/ponudniki'
    | '/video-vsebine'
    | '/clanek/$slug'
    | '/kategorija/$slug'
    | '/novica/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clanki'
    | '/dogodki'
    | '/impressum'
    | '/novice'
    | '/oglasna-deska'
    | '/podpora-mediju'
    | '/pogoji-uporabe'
    | '/politika-zasebnosti'
    | '/ponudniki'
    | '/video-vsebine'
    | '/clanek/$slug'
    | '/kategorija/$slug'
    | '/novica/$slug'
  id:
    | '__root__'
    | '/'
    | '/clanki'
    | '/dogodki'
    | '/impressum'
    | '/novice'
    | '/oglasna-deska'
    | '/podpora-mediju'
    | '/pogoji-uporabe'
    | '/politika-zasebnosti'
    | '/ponudniki'
    | '/video-vsebine'
    | '/clanek/$slug'
    | '/kategorija/$slug'
    | '/novica/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClankiRoute: typeof ClankiRoute
  DogodkiRoute: typeof DogodkiRoute
  ImpressumRoute: typeof ImpressumRoute
  NoviceRoute: typeof NoviceRoute
  OglasnaDeskaRoute: typeof OglasnaDeskaRoute
  PodporaMedijuRoute: typeof PodporaMedijuRoute
  PogojiUporabeRoute: typeof PogojiUporabeRoute
  PolitikaZasebnostiRoute: typeof PolitikaZasebnostiRoute
  PonudnikiRoute: typeof PonudnikiRoute
  VideoVsebineRoute: typeof VideoVsebineRoute
  ClanekSlugRoute: typeof ClanekSlugRoute
  KategorijaSlugRoute: typeof KategorijaSlugRoute
  NovicaSlugRoute: typeof NovicaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-vsebine': {
      id: '/video-vsebine'
      path: '/video-vsebine'
      fullPath: '/video-vsebine'
      preLoaderRoute: typeof VideoVsebineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponudniki': {
      id: '/ponudniki'
      path: '/ponudniki'
      fullPath: '/ponudniki'
      preLoaderRoute: typeof PonudnikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika-zasebnosti': {
      id: '/politika-zasebnosti'
      path: '/politika-zasebnosti'
      fullPath: '/politika-zasebnosti'
      preLoaderRoute: typeof PolitikaZasebnostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pogoji-uporabe': {
      id: '/pogoji-uporabe'
      path: '/pogoji-uporabe'
      fullPath: '/pogoji-uporabe'
      preLoaderRoute: typeof PogojiUporabeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podpora-mediju': {
      id: '/podpora-mediju'
      path: '/podpora-mediju'
      fullPath: '/podpora-mediju'
      preLoaderRoute: typeof PodporaMedijuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oglasna-deska': {
      id: '/oglasna-deska'
      path: '/oglasna-deska'
      fullPath: '/oglasna-deska'
      preLoaderRoute: typeof OglasnaDeskaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novice': {
      id: '/novice'
      path: '/novice'
      fullPath: '/novice'
      preLoaderRoute: typeof NoviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dogodki': {
      id: '/dogodki'
      path: '/dogodki'
      fullPath: '/dogodki'
      preLoaderRoute: typeof DogodkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clanki': {
      id: '/clanki'
      path: '/clanki'
      fullPath: '/clanki'
      preLoaderRoute: typeof ClankiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novica/$slug': {
      id: '/novica/$slug'
      path: '/novica/$slug'
      fullPath: '/novica/$slug'
      preLoaderRoute: typeof NovicaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategorija/$slug': {
      id: '/kategorija/$slug'
      path: '/kategorija/$slug'
      fullPath: '/kategorija/$slug'
      preLoaderRoute: typeof KategorijaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clanek/$slug': {
      id: '/clanek/$slug'
      path: '/clanek/$slug'
      fullPath: '/clanek/$slug'
      preLoaderRoute: typeof ClanekSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClankiRoute: ClankiRoute,
  DogodkiRoute: DogodkiRoute,
  ImpressumRoute: ImpressumRoute,
  NoviceRoute: NoviceRoute,
  OglasnaDeskaRoute: OglasnaDeskaRoute,
  PodporaMedijuRoute: PodporaMedijuRoute,
  PogojiUporabeRoute: PogojiUporabeRoute,
  PolitikaZasebnostiRoute: PolitikaZasebnostiRoute,
  PonudnikiRoute: PonudnikiRoute,
  VideoVsebineRoute: VideoVsebineRoute,
  ClanekSlugRoute: ClanekSlugRoute,
  KategorijaSlugRoute: KategorijaSlugRoute,
  NovicaSlugRoute: NovicaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
